### ISSUE TITLE
httpx.UnsupportedProtocol

### ISSUE THREAD

**Issue by MercureTony** [upstash/degree-guru#7]
I have followed all the steps in the `README`, but I end up with this error everytime I run this code 

`scrapy crawl configurable --logfile degreegurucrawl.log` from the `README`. May you know why ? I haven't found a solution yet. 

`httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.`

An example of the `crawl.yaml`:
<img width="566" alt="Capture d’écran, le 2024-03-15 à 21 34 34" src="https://github.com/upstash/degree-guru/assets/25376741/a34f0f1e-63d1-4870-ac7b-3745f7f65750">

**Comment by CahidArda** [comment]
Hi @MercureTony,

Can you also share the `degreegurucrawl.log` so that I can check where you got this error?

I tried to recreate the error and I was able to recreate it when I ran the crawler without setting the environment variables.

Aret the `UPSTASH_VECTOR_REST_URL` and `UPSTASH_VECTOR_REST_TOKEN` environment variables are set as explained in our [guide](https://github.com/upstash/degree-guru?tab=readme-ov-file#step-1-crawler)?

**Comment by MercureTony** [comment]
Hi @CahidArda !

Thank you for getting back to me.

1. I did set up the environment variables. See here:

<img width="336" alt="Capture d’écran, le 2024-03-16 à 07 41 06" src="https://github.com/upstash/degree-guru/assets/25376741/7131ae43-cd82-4f53-b68d-11b4469ee15f">

2. I take note of this information, I didn't know. I'd love too if you can 😄 !

**Comment by CahidArda** [comment]
Hi @MercureTony,

It looks like you set the variables in the `.env.local` file. That file is for the chatbot. Crawler won't be able to read the environment variables from there. To set the environment variables for chatbot, you need to export them. If you are using mac you can run `export UPSTASH_VECTOR_REST_URL=****`. Then you will be able to run the crawler.

I will look into adding the feature to our crawler so that your website can be crawled. In the meantime, I can suggest crawling the content on your webpage manually to create a vector store. If you populate an Upstash vector store, you can still use our app to run the chatbot.

**Comment by MercureTony** [comment]
Definitely! Thank you for letting me know, I'll test it. And I'll try to implement the feature too in meanwhile. Let's keep in touch. 🕺 😃
